"""first commit

Revision ID: 0360d2e4d958
Revises: 
Create Date: 2021-07-24 02:04:12.139222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0360d2e4d958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # accounts_table = sa.table('user',
    #     sa.column('name', sa.String),
    #     sa.column('email', sa.String)
    # )

    # op.bulk_insert(accounts_table,
    #     [
    #         {'name':'John Smith',
    #                 'email':'abc'},
    #         {'name':'Ed Williams',
    #                 'email':'abc'},
    #         {'name':'Wendy Jones',
    #                 'email':'abc'},
    #     ]
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
